TTTalk/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TTTalk.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^', include('blog.urls')),
    url(r'^ttmusicplayer/', include('TTmusicplayer.urls')),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

blog/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TTTalk.views.home', name='home'),
    url(r'^$','blog.views.show_entries', name='home'),
    url(r'^(?P<page>[0-9]+)/$', 'blog.views.show_entries', name='show'),
    url(r'^article/(?P<entry_id>[0-9]+)$', 'blog.views.entry_detail', name='article'),
)

grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
try: 
    from django.conf.urls import url, patterns
except ImportError: 
    # for Django version less then 1.4
    from django.conf.urls.defaults import url, patterns

from django.views.generic.base import TemplateView
from .views.related import RelatedLookup, M2MLookup, AutocompleteLookup
from .views.switch import switch_user


urlpatterns = patterns('',

    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', RelatedLookup.as_view(), name="grp_related_lookup"),
    url(r'^lookup/m2m/$', M2MLookup.as_view(), name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', AutocompleteLookup.as_view(), name="grp_autocomplete_lookup"),

    # SWITCH USER
    url(r'^switch/user/(?P<object_id>\d+)/$', switch_user, name="grp_switch_user"),

    # GRAPPELLI DOM DOCUMENTATION
    url(r'^grp-doc/change-form/', TemplateView.as_view(template_name='grp_doc/change_form.html'), name="grp_doc_change_form"),
    url(r'^grp-doc/change-list/', TemplateView.as_view(template_name='grp_doc/change_list.html'), name="grp_doc_change_list"),
    url(r'^grp-doc/admin-index/', TemplateView.as_view(template_name='grp_doc/admin_index.html'), name="grp_doc_admin_index"),

    url(r'^grp-doc/tables/', TemplateView.as_view(template_name='grp_doc/tables.html'), name="grp_doc_tables"),

    url(r'^grp-doc/pagination/', TemplateView.as_view(template_name='grp_doc/pagination.html'), name="grp_doc_pagination"),
    url(r'^grp-doc/search-form/', TemplateView.as_view(template_name='grp_doc/search_form.html'), name="grp_doc_search_form"),
    url(r'^grp-doc/filter/', TemplateView.as_view(template_name='grp_doc/filter.html'), name="grp_doc_filter"),
    url(r'^grp-doc/date-hierarchy/', TemplateView.as_view(template_name='grp_doc/date_hierarchy.html'), name="grp_doc_date_hierarchy"),

    url(r'^grp-doc/fieldsets/', TemplateView.as_view(template_name='grp_doc/fieldsets.html'), name="grp_doc_fieldsets"),
    url(r'^grp-doc/errors/', TemplateView.as_view(template_name='grp_doc/errors.html'), name="grp_doc_errors"),
    url(r'^grp-doc/form-fields/', TemplateView.as_view(template_name='grp_doc/form_fields.html'), name="grp_doc_form_fields"),
    url(r'^grp-doc/submit-rows/', TemplateView.as_view(template_name='grp_doc/submit_rows.html'), name="grp_doc_submit_rows"),

    url(r'^grp-doc/modules/', TemplateView.as_view(template_name='grp_doc/modules.html'), name="grp_doc_modules"),
    url(r'^grp-doc/groups/', TemplateView.as_view(template_name='grp_doc/groups.html'), name="grp_doc_groups"),

    url(r'^grp-doc/navigation/', TemplateView.as_view(template_name='grp_doc/navigation.html'), name="grp_doc_navigation"),
    url(r'^grp-doc/context-navigation/', TemplateView.as_view(template_name='grp_doc/context_navigation.html'), name="grp_doc_context_navigation"),

    url(r'^grp-doc/basic-page-structure/', TemplateView.as_view(template_name='grp_doc/basic_page_structure.html'), name="grp_doc_basic_page_structure"),

    url(r'^grp-doc/tools/', TemplateView.as_view(template_name='grp_doc/tools.html'), name="grp_doc_tools"),
    url(r'^grp-doc/object-tools/', TemplateView.as_view(template_name='grp_doc/object_tools.html'), name="grp_doc_object_tools"),

    url(r'^grp-doc/mueller-grid-system-tests/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_tests.html'), name="grp_doc_mueller_grid_system_tests"),
    url(r'^grp-doc/mueller-grid-system/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system.html'), name="grp_doc_mueller_grid_system"),
    url(r'^grp-doc/mueller-grid-system-layouts/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_layouts.html'), name="grp_doc_mueller_grid_system_layouts"),

    url(r'^grp-doc', TemplateView.as_view(template_name='grp_doc/index.html'), name="grp_doc"),

)

blog/models.py
from django.db import models


# Create your models here.
class Music(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    url = models.TextField()

    def __unicode__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=50)

    def __unicode__(self):
        return self.title


class Type(models.Model):
    title = models.CharField(max_length=50)
    icon = models.CharField(max_length=20)

    def __unicode__(self):
        return self.title


class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=5000)
    picture = models.TextField(blank=True)
    demo_url = models.TextField(blank=True)
    code_url = models.TextField(blank=True)
    git = models.CharField(max_length=20, choices=(('bitbucket', 'bitbucket'),('github', 'github')))

    def __unicode__(self):
        return self.title


class Article(models.Model):
    title = models.CharField(max_length=200)
    datetime = models.DateField()
    content = models.TextField()
    summary = models.TextField(max_length=200)
    picture = models.TextField(blank=True)
    views = models.IntegerField(default=0)
    category = models.ForeignKey(Category)
    type = models.ForeignKey(Type)
    music = models.ForeignKey(Music, null=True, blank=True)
    project = models.ForeignKey(Project, null=True, blank=True)

    def __unicode__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=50)
    Article = models.ForeignKey(Article)

    def __unicode__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from models import *
import operator


def show_entries(request, page=1, keywords=None):
    context = {}
    page = int(page)
    if request.GET:
        keywords = request.GET['search']
    if not keywords:
        articles = Article.objects.all()
    else:
        articles = []
        art_dict = {}
        for key in keywords.split(' '):
            tmp = Article.objects.filter(tag__title__iexact=key)
            print 'tmp=', tmp
            for art in tmp:
                if art in art_dict:
                    art_dict[art] += 1
                else:
                    art_dict[art] = 1
                    print 'added'
        sorted_art = sorted(art_dict.iteritems(), operator.itemgetter(1))  # Sorted the articles by relevance
        sorted_art.reverse()  # Sort in descending order
        print sorted_art
        if sorted_art:
            for art_tuple in sorted_art:
                articles.append(art_tuple[0])
        print articles
    art_len = len(articles)
    pages = art_len / 8 + 1  # Get page number of all articles.
    cur_arts = articles[(page-1)*8:page*8-1]  # Get 8 articles from the current page
    context['pages'] = range(pages)  # Total number of pages
    context['page'] = page  # Current page number
    context['articles'] = cur_arts
    context['keywords'] = keywords
    return render(request, 'blog.html', context)


def entry_detail(request, entry_id=0):
    context = {}
    entry = Article.objects.get(pk=entry_id)
    if entry_id not in request.session:
        entry.views += 1
        entry.save()
        request.session[entry_id] = True
    context['article'] = entry
    return render(request, 'entry.html', context)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/semantic.css' %}">
    <link rel="stylesheet" href="{% static 'css/ttstyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/codehighlight.css' %}">
</head>
<body>
    {% block sidebar %}
    {% endblock %}

    <div class="upper">
{#        <div class="ui blue huge launch right attached button" id="left-button" status="lock">#}
{#          <i class="icon lock layout"></i>#}
{#          <span class="text" style="display: none;">Menu</span>#}
{#        </div>#}
        <div class="ui grid m0">
            <div class="one wide column">
            </div>
            <div class="eleven wide column" style="margin-top: 0;">
                <div class="placeholder50">
                    {% if message %}
                    <div class="ui success message" style="border-radius: 0 0 0.8em 0.8em;
                    border-bottom: 1px solid #009b4e;
                    border-left: 1px solid #009b4e;
                    border-right: 1px solid #009b4e;">
                      <i class="close icon"></i>
                        {{ message }}
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="ui grid m0">
            <div class="one wide column">
            </div>
            <div class="eleven wide column">
                <div class="wrapper">
                    <header class="header-part">
                        <img class="circular ui image" id="avatar" src="{% static 'img/avatar.jpeg' %}">
                        <img class="ui header" src="{% static 'img/logo1.png' %}">
                    </header>
                    <div class="ui menu tt">
                        <a class="item" href="{% url 'home' %}">
                            <i class="home icon"></i> Home
                        </a>
                        <a class="item">
                            <i class="cloud icon"></i> Portfolio
                        </a>
                        <a class="item">
                            <i class="music icon"></i> Music
                        </a>
                        <a class="item">
                            <i class="music icon"></i> About
                        </a>
                        <div class="right menu">
                            <div class="item">
                              <div class="ui icon input">
                                <input type="text" placeholder="Search...">
                                <i class="search link icon"></i>
                              </div>
                            </div>
                        </div>
                    </div>
                    {% block body %}
                    {% endblock %}
                <div class="placeholder90">
                </div>
                </div>
            </div>
        </div>
        <div class="placeholder90"></div>
    <div class="ui dimmer hidden">
        <div class="content">
            <div class="center">Free!</div>
        </div>
    </div>
    </div>
    <div class="footer">
        <div class="inner">
            <div style="text-align: center">Powered By 丸子哥略屌</div>
        </div>
    </div>
</body>


    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static 'js/semantic.js' %}"></script>
    <script type="text/javascript">
        $("document").ready(function()
        {
{#            $sideBarButton = $(".launch.button"),#}
            $('#avatar').mouseenter(function(){$(this).transition('tada')});
            $tag = $(".tag");
            $tag.each(function(){
                $(this).attr('href', $(this).attr('href')+'?search='+$(this).text());
            });

{#            $sideBarButton.mouseenter(function()#}
{#            {#}
{#		        $(this).stop().animate({width: '164px'}, 200,function()#}
{#                {#}
{#                    if($(this).attr('status') == 'lock'){#}
{#                        $(this).find('.lock').addClass('unlock alternate').removeClass('lock');#}
{#                    }#}
{#                    else{#}
{#                        $(this).find('.unlock').addClass('alternate');#}
{#                    }#}
{#                    $(this).find('.text').show();#}
{#                });#}
{#	        }).mouseleave(function (event)#}
{#            {#}
{#		        $(this).find('.text').hide();#}
{#                if($(this).attr('status') == 'lock'){#}
{#                    $(this).find('.icon').addClass('lock').removeClass('unlock alternate');#}
{#                }#}
{#                else{#}
{#                    $(this).find('.icon').removeClass('alternate');#}
{#                }#}
{#		        $(this).stop().animate({width: '70px'}, 200);#}
{#	        });#}
{#            $sideBarButton.click(function(){#}
{#            $('.ui.sidebar').sidebar('toggle');#}
{#            });#}
       });

        function onClick() {

{#            if ($(this).attr('status') == 'lock') {#}
{#                $(this).attr('status', 'unlock');#}
{#                $(".eleven").addClass('thirteen').removeClass('eleven');#}
{#            }#}
{#            else {#}
{#                $(this).attr('status', 'lock');#}
{#                $(".thirteen").addClass('eleven').removeClass('thirteen');#}
{#            }#}



{#            if ($upper.hasClass('dimmed')) {#}
{#                $upper.dimmer('hide');#}
{#            }#}
{#            else {#}
{#                $upper.dimmer({closable: false#}
{#                              }).dimmer('show');#}
{#            }#}
        }
    </script>
    {% block js %}
    {% endblock %}
</html>

templates/blog.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load markdown %}

{% block title %}
    Blog
{% endblock %}

{% block sidebar %}
    <div class="ui styled sidebar" style="background-image: url(/static/img/bg_yellow_light.gif)">
      <h3 class="ui header">You Might Like</h3>
      <div class="ui fluid vertical menu">
        <a class="item">
          <i class="chat outline icon"></i>
          More by this author
        </a>
        <a class="item">
          <i class="text file icon"></i>
          Suggested Articles
        </a>
      </div>
      <h3 class="ui header">Contact Us</h3>
      <div class="ui form">
        <div class="field">
          <label>Name</label>
          <div class="ui icon input">
            <i class="user icon"></i>
            <input type="text" data-placeholder="Name">
          </div>
        </div>
        <div class="field">
          <label>Message</label>
          <textarea></textarea>
        </div>
        <div class="ui black fluid button">Submit</div>
      </div>
    </div>
{% endblock %}

{% block body %}
    <div class="TTcontent">
    {% if not articles %}
        <div class="empty">No Result</div>
    {% endif %}
    {% for article in articles %}
        <div class="article">
        <div class="entryheader">
            <div class="entrytype">
                <div id="label" class="ui ribbon label">
                    <i class="{{ article.type.icon }} icon"></i>
                </div>
            </div>
            {% if article.type.title == "Project" %}
                <div class="ui items">
                <div class="item" id="project">
                    <div class="image">
                      <img class="ui huge image" src="{{ article.project.picture }}">
                      <a class="like ui corner label">
                        <i class="like icon"></i>
                      </a>
                    </div>
                    <div class="content">
                      <div class="name">{{ article.project.title }}</div>
                      <p class="description">{{ article.project.description }}</p>
                        <div class="ui buttons">
                            <a class="ui animated button" href="{{ article.project.code_url }}">
                                <div class="visible content">
                                    Code
                                </div>
                                <div class="hidden content">
                                    <i class="{{ article.project.git }} icon"></i>
                                </div>
                            </a>
                            <div class="or"></div>
                            <a class="ui positive button" href="{{ article.project.demo_url }}">Demo</a>
                        </div>
                      <div class="extra">
                          199 votes
                      </div>
                    </div>
                </div>
                </div>
            {% else %}
                <h1><a href="{% url 'article' article.id %}">{{ article.title }}</a> | <a id="category" href="">{{ article.category }}</a></h1>
                <i class="calendar icon"></i>
                <time class="ui floated left">Posted on: {{ article.datetime }}</time>
                <tag class="ui floated right">
                <i class="tags basic icon"></i>
                {% for tag in article.tag_set.all %}
                    <a id="tag" class="ui tag" href="{% url 'show' 1 %}">{{ tag }}</a>
                {% endfor %}
                </tag>
                <div class="entrybody">
                {{ article.summary |markdown|safe }}
                </div>
                <p>...</p>
            {% endif %}
        <div>
            <p class="floatright" id="views">Viewed {{ article.views }} times</p>
            <i class="icon right arrow"></i><a class="detail" href="{% url 'article' article.id %}">Read More</a>
        </div>
        <div id="entryd" class="ui horizontal icon divider">
            <i class="circular {{ article.type.icon }} icon"></i>
        </div>
    </div>
    </div>
    {% endfor %}
    </div>
    <div class="ui divider">
    </div>
    <div class="ui grid">
        <div class="four wide column">
            <a id="previous" class="ui black button {% if page == 1 %} disabled {% endif %} left" href="{% url 'show' page|add:-1 %}">Previous</a>
        </div>
        <div class="eight wide column" style="text-align: center;">
            <div class="ui borderless pagination menu">
                {% for p in pages %}
                <a class="item {% if page == forloop.counter %} disabled {% endif %}" href="{% url 'show' forloop.counter %}">{{ forloop.counter }}</a>
                {% endfor %}
            </div>
        </div>
        <div class="four wide column">
            <a id="next" class="ui black {% if page == pages|length %} disabled {% endif %} button floatright" href="{% url 'show' page|add:1 %}">Next</a>
        </div>
    </div>
{% endblock %}

templates/entry.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load markdown %}

{% block title %}
    Blog
{% endblock %}


{% block sidebar %}
    <div class="ui styled sidebar" style="background-image: url(/static/img/bg_yellow_light.gif)">
    </div>
{% endblock %}

{% block body %}
    <div class="TTcontent">
        <div class="article">
        <div class="entryheader">
            <div class="entrytype">
                <div id="label" class="ui ribbon label">
                    <i class="{{ article.type.icon }} icon"></i>
                </div>
            </div>
            <h1>{{ article.title }} | <a id="category" href="">{{ article.category }}</a></h1>
            <i class="calendar icon"></i>
            <time class="ui floated left">Posted on: {{ article.datetime }}</time>
            <tag class="ui floated right">
            <i class="tags basic icon"></i>
            <form action="{% url 'show' 1 %}" method="get" id="tagform">
            {% for tag in article.tag_set.all %}
                <a id="tag" class="ui tag" href="{% url 'show' 1 %}">{{ tag }}</a>
            {% endfor %}
            </form>
            </tag>
        </div>
        <div class="entrybody">
        {% if article.music %}
        <div id="music-wrapper">
            <audio id="musicplayer">
                <source src="{{ article.music.url }}" type="audio/mp3" />
            </audio>
            <div id="defaultBar">
                <div id="progressBar"></div><!--
                --><div id="progressHead"></div>
            </div>
            <div id="controlBtn">
                <i class="play icon large" id="controlIcon"></i>
            </div>
            <div id="captain">
                <p class="musictitle">{{ article.music.title }}</p>
                <p class="author">covered by {{ article.music.author }}</p>
            </div>
        </div>
        {% endif %}
        {{ article.content |markdown |safe}}
        </div>
        </div>
        <div>
        &nbsp;
            <p id="views" class="floatright">Viewed {{ article.views }} times</p>
        </div>
{#        <div>#}
{#            <i class="icon right arrow"></i><a href="">Read More</a>#}
{#        </div>#}
        <div class="ui horizontal icon divider">
            <i class="circular {{ article.type.icon }} icon"></i>
        </div>
        <div class="empty">Be The First To Comment Here!</div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/ttmusicplayer.js' %}"></script>
{% endblock %}